language: perl
before_script:
  - "git config --global user.email 'you@example.com'"
  - "git config --global user.name 'Your Name'"
script: perl Build.PL && ./Build build && ./Build test
perl:
  - 5.16
  - 5.14
